"""
Django settings for paksite project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from configurations import Configuration

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


class Dev(Configuration):
    DEBUG = True
    NO_EMAIL = False

    # PROD KEY 
    FANTASY_DATA_KEY = os.environ.get('FANTASY_DATA_KEY')
    FANTASY_DATA_PROJECTIONS_KEY = os.environ.get('FANTASY_DATA_PROJECTIONS_KEY')

    FANTASY_DATA_KEY_MLB = os.environ.get('FANTASY_DATA_KEY_MLB')
    FANTASY_DATA_PROJECTIONS_KEY_MLB = os.environ.get('FANTASY_DATA_PROJECTIONS_KEY_MLB')

    SECRET_KEY = os.environ.get('SECRET_KEY')

    BROKER_URL = 'amqp://guest:guest@localhost:5672//'
    CELERY_RESULT_BACKEND = 'amqp'
    ALLOWED_HOSTS = ['localhost', 'code.3pakapi.net', '*', 'apps.3pak.com']

    # Application definition
    INSTALLED_APPS = (
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django_extensions',
        'app',
        'rest_framework',
        'rest_framework.authtoken',
        'rest_auth',
        'django.contrib.humanize',
        # 'push_notifications',
        'corsheaders',
    )

    REST_AUTH_SERIALIZERS = {
        #    'PASSWORD_RESET_SERIALIZER': test
    }

    # PUSH_NOTIFICATIONS_SETTINGS = {
    #    "GCM_API_KEY": "******,
    #    "APNS_CERTIFICATE": "/home/ubuntu/site/3pak-server/cert/push/ProdAPN.pem",
    #    "APNS_HOST": "gateway.push.apple.com"
    # }

    MIDDLEWARE_CLASSES = (
        'django.contrib.sessions.middleware.SessionMiddleware',
        'corsheaders.middleware.CorsMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'django.middleware.security.SecurityMiddleware',
        'app.middlelog.MiddleLog',
    )

    ROOT_URLCONF = 'paksite.urls'

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [
                os.path.join(BASE_DIR, 'app/templates'),
                os.path.join(BASE_DIR, 'app/templates/leaderboard'),
            ],
            'APP_DIRS': True,
            'OPTIONS': {
                'debug': DEBUG,
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

    WSGI_APPLICATION = 'paksite.wsgi.application'

    # Database
    # https://docs.djangoproject.com/en/1.8/ref/settings/#databases

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'threepak',
            'USER': 'root',
            'PASSWORD': 'xx'
        }
    }

    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_USE_TLS = True
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    # EMAIL_HOST_USER = 'api@play3pak.com'
    # EMAIL_HOST_PASSWORD = 'djangobackend'
    # EMAIL_HOST_USER = 'support-team@3pak.com'
    # EMAIL_HOST_PASSWORD = 'Or^ilXD1JN5f'
    EMAIL_HOST_USER = '3paksystem@3pak.com'
    EMAIL_HOST_PASSWORD = 'one4threepak'

    DEFAULT_FROM_EMAIL = 'support-team@play3pak.com'

    # Internationalization
    # https://docs.djangoproject.com/en/1.8/topics/i18n/

    LANGUAGE_CODE = 'en-us'

    TIME_ZONE = 'US/Eastern'
    USE_I18N = True
    USE_L10N = True
    USE_TZ = True

    STRIPE_TEST_SECRET = os.environ.get('STRIPE_TEST_SECRET')
    STRIPE_TEST_PUB = os.environ.get('STRIPE_TEST_PUB')
    STRIPE_LIVE_SECRET = os.environ.get('STRIPE_LIVE_SECRET')
    STRIPE_LIVE_PUB = os.environ.get('STRIPE_LIVE_PUB')

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/1.8/howto/static-files/

    MEDIA_URL = '/media/'
    # Additional locations of static files

    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static')

    STATICFILES_DIRS = (
        os.path.join(BASE_DIR, "app/templates/leaderboard/static"),
        '/usr/local/lib/python2.7/dist-packages/django/contrib/admin/static'
    )
    STATICFILES_FINDERS = (
        "django.contrib.staticfiles.finders.FileSystemFinder",
        "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    )

    MEDIA_ROOT = '/home/pc/src/3pak-server/media'

    REST_FRAMEWORK = {
        'PAGE_SIZE': 10,
        'DEFAULT_AUTHENTICATION_CLASSES': (
            'rest_framework.authentication.BasicAuthentication',
            'rest_framework.authentication.SessionAuthentication',
            'rest_framework.authentication.TokenAuthentication',
        ),
        'DEFAULT_RENDERER_CLASSES': (
            'rest_framework.renderers.JSONRenderer',
            'rest_framework.renderers.BrowsableAPIRenderer',
        ),
        'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    }

    CORS_ORIGIN_ALLOW_ALL = True
    CORS_ALLOW_CREDENTIALS = True
    CORS_REPLACE_HTTPS_REFERER = True

    PAK_SITE_ADDRESS = 'https://apps.3pak.com/'
    PAK_DEFAULT_CUSTOMERPROFILE = 'app'
    try:
        execfile(os.path.join(BASE_DIR, 'settings_local.py'))
        print "found file"
    except IOError:
        print "unable to find file"


class Production(Dev):
    DEBUG = True
    MEDIA_ROOT = '/var/www/media/'
    STATIC_ROOT = '/var/www/static/'

    PAK_SITE_ADDRESS = 'https://apps.3pak.com/'
    PAK_DEFAULT_CUSTOMERPROFILE = 'app'
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
                'datefmt': "%d/%b/%Y %H:%M:%S"
            },
            'simple': {
                'format': '%(levelname)s %(message)s'
            },
        },
        'handlers': {
            'file': {
                'level': 'DEBUG',
                'class': 'logging.FileHandler',
                'filename': '/home/ubuntu/site/3pak-server/logs/pak.log',
                'formatter': 'verbose'
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'propagate': True,
                'level': 'ERROR',
            },
            'app': {
                'handlers': ['file'],
                'propagate': True,
                'level': 'DEBUG',
            },
        }
    }

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'threepak',
            'HOST': 'localhost',
            'USER': 'root',
            'PASSWORD': 'xx'
        }
    }
    BROKER_URL = 'amqp://guest:guest@172.31.16.87:5672//'
