# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemlb',
            name='Channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
