# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180604_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='button_font_color',
            field=models.CharField(blank=True, default=b'#FDFDFD', help_text=b'button text color (overrides dark/light)', max_length=30),
        ),
    ]
