# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 21:29
from __future__ import unicode_literals

from django.db import migrations

def remove_innings(apps, schema_editor):
    InningMLB = apps.get_model('app', 'InningMLB')
    InningMLB.objects.all().delete()
    
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customerprofile_button_font_color'),
    ]

    operations = [
        migrations.RunPython(remove_innings, reverse_code=migrations.RunPython.noop),

    ]
