# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180628_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inningmlb',
            name='GameID',
            field=models.IntegerField(unique=True),
        ),
    ]
