# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180628_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesMLB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_start', models.DateTimeField(blank=True, null=True)),
                ('series_end', models.DateTimeField(blank=True, null=True)),
                ('HomeTeam', models.CharField(default=b'', max_length=10)),
                ('AwayTeam', models.CharField(default=b'', max_length=10)),
            ],
        ),
    ]
